# -*- coding: utf-8 -*-
"""Python Programming - 3 (입출력)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YSKeCL3hB1wWTrOMCO37FWxmdJxk_hOi

# 파이썬에서 입력받는 방식
---
변수명 = input()
예시: a = input()
* input() 함수는 자동으로 문자열로 입력받는다.

---
정수 입력받는 방법
* 변수명 = int(input())

---
실수 입력받는 방법
* 변수명 = float(input())

---
"""

name = input("이름을 입력하세요:")
print("당신의 이름은 %s입니다." % name)

age = int(input("당신의 나이를 입력하세요:"))
print("당신의 나이는 %d세입니다." % age)

record = float(input("100m 달리기 기록을 입력하시오 : "))
print("100m 달리기 기록은 %f 초 입니다." % record)
# %f를 출력하면 소수점 6번째 자리까지 출력
#소수점 둘째 자리까지 출력하려면 %는 그대로 쓰고 .2f로 쓴다
#셋째자리 -> .3f

#정 사각형 한 변의 길이를 입력받고 넓이 출력
#실수형으로 입력받고 실수형으로 출력
a = float(input("정사각형 한 변의 길이 : "))
b=a*a
print("정사각형의 넓이는 %.2f 입니다." % b)

#원의 반지름을 입력 받아서 원 둘레, 원 넓이 출력
#소수점 셋째 자리까지 출력
r = int(input("원의 반지름:"))
a = 2*3.14*r
b = 3.14*r*r
print("원 둘레는 %.3f 이고 원넓이는 %.3f 입니다." % (a,b))

a,b = map(int, input("숫자 두 개를 띄어쓰기 간격으로 입력: ").split())
print(a, b)

#직사각형의 가로와 세로를 동시에 입력받아서 넓이 출력 (실수형)
#소수점 둘째자리
a, b = map(float, input("직사각형의 가로와 세로를 띄어쓰기 간격으로 입력: ").split())
c=a*b
print("직사각형의 넓이는 %.2f 입니다" %c)

a, b = map(float, input("직사각형의 가로와 세로를 띄어쓰기 간격으로 입력: ").split())
print("직사각형의 넓이는 %.2f 입니다."%(a*b))