# -*- coding: utf-8 -*-
"""Python Programming - 5(반복 구조)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eYi1H_0TSDQ3EuGizihNedbYosvlXI-R
"""

for i in range(5):
  print("딸기")

for i in range(5):
  print(i)

for i in range(1,5):
  print(i)

for i in range(1,9,3):
  print(i)

for i in range(5,2,-1):
  print(i)

for i in range(10,0,-1):
  print(i)

for i in range(10,0,-1):
  print(i, end= " ")

for i in range(2,11,2):
  print(i)

for i in range(1,6):
  print(i*"*")

for i in range(5,0,-1):
  print(i*"*")

a = int(input())
for i in range(1,10):
  print("%d * %d = %d" %(a,i,(a*i)))

sum=0
a = int(input())
for i in range(1,a+1):
  sum= sum+i
print(sum)

f = 1
a = int(input())
for i in range(a,0,-1):
  f = f*i
print(f)

a,b = map(int,input().split())
if a%2 == 0:
  a= a+1
for i in range(a,b+1,2):
  print(i)

a = 2
while a<5:
  print(a)
  a = a+1

a = 2
while a<5:
  a = a+1
  print(a)

a = 0
while a <10 :
  a = a + 1
  print(a)
  if a == 10:
    print("끝")

a = 0
while a < 5:
  a = a+1
  print("*"*a)

a = 6
while a > 1:
  a = a-1
  print("*"*a)

sum = 0 #누적 합계를 계산하기 위해 저장
n = -1 #조건식 성립을 위한 초깃값
while n!=0 : #n 값이 0이 아니면 계속 실행
  n = int(input())
  sum = sum + n
print("누적 합계는 %d 입니다."%sum)

#랜덤 숫자 맞히기
import random
ans = random.randint(1,10) #1부터 10 사이의 무작위 수를 생성
n = -1 #사람의 추측을 저장할 변수
while n != ans : #정답을 못 맞히면 계속 실행
  n = int(input("정답을 맞혀보세요: "))
print("정답은 %d"%ans)

#랜덤 숫자 맞히기
import random
ans = random.randint(1,10) #1부터 10 사이의 무작위 수를 생성
n = -1 #사람의 추측을 저장할 변수
cnt = 0
while n != ans : #정답을 못 맞히면 계속 실행
  n = int(input("정답을 맞혀보세요: "))
  cnt = cnt +1
print("정답은 %d"%ans)
print("%d번만에 맞혔습니다."%cnt)

tot = 100
sum = 0
while sum <= tot:
  n = int(input("입력: "))
  sum = sum + n
print("초과되었습니다. 현재 합계 : %d"%sum)