# -*- coding: utf-8 -*-
"""python programming -1 (변수와 자료형)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11WM_JgMFdhDYZhzhvYL3a-jFudB3s13j

# 변수
---
변수란 프로그래밍에서 **값이 저장되는 공간**

---
"""

32

a = 20
#프로그래밍에서 =의 의미는 할당(allocation)이다.
#a=20의 의미는 a라는 상자(변수)안에 20이라는 값을 할당한다.
a

b = 7 #b라는 변수 안에 7이 할당됨
print(b) #print는 출력하기 위한 함수
print(b)
print(b)

a=7
b=a
a=10
print(b)

"""# 자료형
---
자료형이란 저장된 데이터의 유형을 뜻한다

---
자료형의 종류
* 정수형(int) : 소수점이 없는 숫자
* 실수형(float) : 소수점이 있는 숫자
* 문자열(str) : 문자/글자
* 논리형(bool) : 참/거짓
"""

# 정수 자료형
a=7 # 변수 a의 자료형은 정수형
print(a)
print(type (a))

#실수 자료형
pi=3.141592 #변수 pi의 자료형은 실수형
print(pi)
print(type(pi))

#문자열
c= '가나다라'
print(c)
print(type(c))

from os import fchdir
#논리 자료형(참 / 거짓)
t = True
f = False
print(t and f) #and 는 둘다 참이어야 참
print(t or f) #or은 둘 중 하나만 참이어도 참
print(not t)#not은 참/거짓을 반대로 전환
print(type(f))

print(not (t or f))
print((not t) or f) #파이썬에서도 괄호가 먼저 계산된다.

