# -*- coding: utf-8 -*-
"""Python Programming - 6(중첩 제어 구조)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oXa0cnMlaIV_HuYrScAaod6Dk7lRyv2R

# 중첩 제어 구조
---
* 중첩 제어 구조란, 제어구조 안에 제어 구조가 1개 이상 존재하는 문법을 의미
---
> **선택 구조 안에 선택 구조**

> **선택 구조 안에 반복 구조**

> **반복 구조 안에 선택 구조**

> **반복 구조 안에 반복 구조**
---
"""

#선택구조 안에 선택구조(연령에 따른 입장료 계산)
age = int(input("나이를 입력하세요: "))
fee = 14000
if age <= 9 or age >= 65 :
  if age <= 9:
    print("요금은 %d입니다."%(fee * 0.8))
  else :
    print("요금은 %d입니다."%(fee * 0.7))
else:
  print("요금은 %d 입니다."%fee)

#선택구조 안에 반복구조(카운트)
#입력된 수가 양수 : 카운트 다운(1), 입력된 수가 음수 : 카운트 업(-1)
a = int(input("정수 입력: "))
if a <0 :
  for i in range(a,0):
    print(i)
else:
  for i in range(a,0,-1):
    print(i)

#선택구조 안에 반복구조(별찍기)
a = int(input("몇줄 출력할까요: "))
b = int(input("1?2?: "))
if b == 1:
  for i in range(1,a+1):
    print(i*"*")
elif b == 2:
  for i in range(a,0,-1):
    print(i*"*")
else :
  print("닥쳐")

#반복 구조 안에 선택 구조
# continue - 반복문에서는 건너뛰기
n = int(input("n?"))
for i in range(1,n+1):
  if i%2==1: #i가 홀수인 경우
    continue
  else : #i가 짝수인 경우
    print(i)

# 반복구조 안에 선택구조
# 입력되는 모든 수를 더하는 프로그램
# break - 반복문 탈출
a = 100000
sum = 0 #합계를 저장
for i in range(a):# a번 반복
  n = int(input("더할 숫자 : (0누르면 종료)"))
  if n == 0: #종료 조건에 해당
    print("종료합니다.")
    break
  else :
    sum = sum + n
print("누적 합계는 %d"%sum)

#반복구조 안에 반복구조(구구단 출력)
#1단부터 9단까지 모두 출력
for i in range(1,10):
  for j in range(1,10):
    print("%d * %d = %d"%(i,j,i*j))

#반복구조 응용 예제
n = int(input("n?"))
x = int(input("x?"))
for i in range(1,n+1):
  for j in range(x):
    print(i+j+i*j)

import random
ch = int(input("몇번의 기회?"))
rng = int(input("범위는 어디까지?"))
rn = random.randint(1,rng)
for i in range(1,ch+1):
  ans = int(input("정답을 맞혀보세요."))
  if ans == rn:
    print("%d번만에 정답"%i)
    break
  elif ans > rn:
    print("down")
  else:
    print("up")

"""# #9610(중첩 제어 구조)  [#9610](https://www.acmicpc.net/problem/9610)
2차원 좌표 상의 여러 점의 좌표 (x,y)가 주어졌을 때, 각 사분면과 축에 점이 몇 개 있는지 구하는 프로그램을 작성하시오.
"""

n = int(input("좌표 개수: "))
a, b, c, d, w = 0, 0, 0, 0, 0
for i in range(n):
  x, y = map(int,input("좌표 입력: ").split())
  if x > 0 :
    if y > 0:
      a = a+1
    elif y <0:
      c = c+1
    else:
      w = w+1
  elif x < 0:
    if y > 0:
      b = b+1
    elif y< 0:
      d = d+1
    else:
      w = w+1
  else:
    w = w+1
print("1사분면 위 좌표 개수 : %d"%a)
print("2사분면 위 좌표 개수 : %d"%b)
print("3사분면 위 좌표 개수 : %d"%c)
print("4사분면 위 좌표 개수 : %d"%d)
print("축 위 좌표 개수 : %d"%w)

"""# #10103(중첩 제어 구조) [#10103](https://www.acmicpc.net/problem/10103)
예원이와 수연이는 게임을 하고 있다.

게임을 시작하는 시점에서, 두 사람의 점수는 모두 100점이다.

게임은
여섯 면 주사위를 사용하며, 라운드로 진행된다. 매 라운드마다, 각 사람은 주사위를 던진다. 낮은 숫자가 나온 사람은 상대편
주사위에 나온 숫자만큼 점수를 잃게 된다. 두 사람의 주사위가 같은 숫자가 나온 경우에는 아무도 점수를 잃지 않는다.

게임이 끝난 이후에 두 사람의 점수를 구하고, 누가 이겼는지 혹은 비겼는지 결과를 출력하시오.
"""

r = int(input("몇라운드?"))
ks = 100
js = 100
for i in range(r):
  a, b= map(int, input("김과 조의 주사위 눈:").split())
  if a > b:
    js = js- a
  elif a < b:
    ks = ks- b
  else :
    pass
print("예원의 점수는 %d 입니다."%ks)
print("수연의 점수는 %d 입니다."%js)
if ks < js:
  print("조수연 승")
elif js <ks:
  print("김예원 승")
else:
  print("비김")