# -*- coding: utf-8 -*-
"""Python Programming - 2 (연산자)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sGNIskjL8UMzhwkeGOxpolSDo3gXWq02

# 연산자
---
연산자란, 파이썬에서 변수나 함수를 계산하기 위한 장치


---
연산자의 종류
1. 할당 연산자(=)
* 예시) 변수 이름 = 변수에 할당하려는 값
* a = 10 (변수 a와 b에 정수 10을 할당)
* a = b (변수 a에 변수 b에 들어있는 값을 할당)
* a = b = 10 (변수 a와 b에 정수 10을 할당,
이때, b가 먼저 할당되고 그다음 a 할당)

**파이썬에서는 자료형이 자동으로 부여된다. 예를 들어, 컴파일 언어인 c언어에서는 int a = 10 이라고 작성해야 하지만 파이썬에서는 a = 10이라고만 작성해도 변수 a가 자동적으로 정수형 변수가 된다.
만약 a = '10'이라고 작성하면 변수 a의 자료형은 문자열이 된다.**
---
2. 산술 연산자
* '+': 더하기
* '-': 빼기
* '*': 곱하기
* '/': 나누기
* '%': 나머지
* '//': 몫(만일, 나눈 후 몫이 소수점이면 내림)
* '**': 제곱
---
3. 비교 연산자(출력은 True 아니면 False 형식)
* '==': 같으면 참
* '!=': 같지 않으면 참
* '>': 왼쪽 값이 오른쪽 값보다 크면 참
* '<': 오른쪽 값이 왼쪽 값보다 크면 참
* '>=': 왼쪽 값이 오른쪽 값보다 크거나 같으면 참
* '<=': 오른쪽 값이 왼쪽 값보다 크거나 같으면 참
---
4. 논리 연산자(출력은 True 아니면 False 형식)
* and, &: 둘 다 참이어야 참
* or, |: 둘 중 하나만 참이어도 참
* not: 거짓이면 참, 참이면 거짓으로 전환
* (중요) True 와 False를 산술 연산(더하기, 빼기, 곱하기, 나누기) 하면 정수형으로 자동 변환됨.
---
"""

a=b=c=30
print(a, b, c)
b = b + 3 #변수 b에 3을 더한 값을 변수 b에 할당
print(b)

#산술 연산자
d = 3
e = 4
f = 5
print(d + e) #7
print(f - d) #2
print(d * f) #15
print(d/f) #3/5=0.6 정수형/정수형은 나누어 떨어져도 실수형으로 자동 변환
print(type(d/f)) #정수/정수 연산 시 실수형 형변환 확인

#산술 연산자 (몫 //, 나머지 %, 제곱 **)
가, 나 =17, 4
print(가//나) #가(17)를 나(4)로 나눈 몫
print(가%나) #가(17)를 나(4)로 나눈 나머지
print(나**가) #나(4)의 가(17)제곱

가나다라 = 3
q = '가나다라' #변수 q에 문자열 '가나다라'를 할당
print(q)
q = 가나다라 #변수 q에 변수 가나다라 값을 할당
print(q)

r = '집가고싶다'
print(r*100) #문자열 * 숫자는 해당 문자열을 숫자만큼 복붙해서 출력
t = '졸리다'
print(r+t)

r=input()
print(r * 100)

"""# 문자열과 산술 연산 정리
---
* 문자열 + 문자열 가능
* 문자열 * 정수 가능
* 문자열 * 정수형 변수 가능
* 문자열 * 문자열은 불가능
* 문자열 + 정수형 변수 불가능
"""

#비교 연산자
a, b = 5, 7
print(a==b) #a와 b가 같냐?
print(a!=b) #a와 b가 다르냐?
print(a > b) #a가 b보다 크냐?
a = a + 4
print(a > b)
print(a < b)  #a가 b보다 작냐?
a = a - 10
print(a < b)

c, d = 1, 0
print(c >= d) #c가 d보다 크거나 같냐?
d = d+1
print(c >= d)
d = d+1
print(c >= d)

e, f =0, 0
print(e <= f) #e가 f보다 작거나 같냐?
f = f - 1
print(e <= f)

#논리 연산자
t, f = True, False
print(t and f)
print(t & f) #&는 and의 의미
print(t or f)
print(t | f) #|는 or의 의미
print(not t, not f) #not는 반전

#논리형 변수의 산술 연산
t, f = True, False
print(t + f)
print(t - f)
print(t * f)
print(f / t)
a = t + f
b = t-f
c = t*f
d = f/t
print(type(a), type(b),type(c), type(d))

#자료형 변환
a = 3 #정수형 변수
print(a, type(a))
a = str(a) #변수 a의 자료형을 문자열로 변환
print(a, type(a))
a = float(a) #변수 a의 자료형을 실수형으로 변환
print(a, type(a))

#문자열을 정수 자료형으로 변환한 다음에 다시 실수형으로 변환
b ='8'#문자열
b = int(b) #정수 자료형으로 변환하기 위한 코드 입력
print(b, type(b))
b = float(b) #실수 자료형으로 변환하기 위한 코드 입력
print(b, type(b))